### ISSUE TITLE
Ensure that no variables changed meaning during data generation

### ISSUE THREAD

**Issue by arilamstein** [arilamstein/censusdis-streamlit#19]
This issue is described in detail here: https://github.com/censusdis/censusdis/issues/264

I need to write code to do this, and then apply it to everything in the data generation script.

One thought (maybe not the right one): Use a defaultdict of lists. The keys would be the variable's labels. The values would be a list of years. If the length of the dict winds up being 0, then just print out `.`.  If it's longer than that, print out something like 

"variable foo maps to more than one label during the sample period:
  * bar: years <list>
  * baz: years <list>"

**Comment by arilamstein** [comment]
Close by https://github.com/arilamstein/censusdis-streamlit/pull/22

**Comment by arilamstein** [comment]
Duplicating the comment I made in the censusdis package here as well just for completeness:

> In case anyone winds up reading this and wanting to do something similar, feel free to use the code I wrote to solve this for myself. This function takes an ACS, variable and iterable of years. It returns a dict where each key is a label used for that variable, and the value is a list of years that label was used:

> https://github.com/arilamstein/censusdis-streamlit/blob/02a866a1b4be08b803b1eabf4725284eb034923f/validate_variable_labels.py#L7

> In my particular case I am creating a time series df of multiple variables over the course of the entire ACS1. I wrote a function that prints debug info about the labels each variable has had over the course of the dataset. This helps me make sure that errors like this are not creeping into my app. You can see that function here:

> https://github.com/arilamstein/censusdis-streamlit/blob/02a866a1b4be08b803b1eabf4725284eb034923f/validate_variable_labels.py#L50

**Comment by vengroff** [comment]
Nice. Note that for the first argument of `get_unique_labels_for_variables`, and dataset from `censusdis.datasets.*` should work fine, not just the ACS ones. So I would tend to name that first argument `dataset` instead of `acs`. But if you make that change test it. Don't just take my word for it.
