### ISSUE TITLE
median income 

### ISSUE THREAD

**Issue by CensusCharles** [arilamstein/censusdis-streamlit#3]
3/4/2024  Currently, when rolling (hovering) over the map, the tooltip pop-up shows median income in the form:
153.292k
I think it would be more readable and more consistent with how the amount is shown in the table if median income were shown in this form:
153,292

**Comment by arilamstein** [comment]
I agree. It looks like plotly called this "hover text". A good google search for this seems to be "px.choropleth_map hover text"

**Comment by CensusCharles** [comment]
[like]  Charles R Jones (CENSUS/ACSO FED) reacted to your message:
________________________________

**Comment by arilamstein** [comment]
Here is how to solve this problem.
 * Section "Disabling or customizing hover of columns in plotly express" from [this](https://plotly.com/python/hover-text-and-formatting/#customizing-hover-text-with-plotly-express) page.
 
It says:

> For an existing column, the values can be ... a formatting string starting with : for numbers [d3-format's syntax](https://github.com/d3/d3-3.x-api-reference/blob/master/Formatting.md#d3_forma), and | for dates in [d3-time-format's syntax](https://github.com/d3/d3-time-format), for example :.3f, |%a.

So I need to spend some time with that d3 page.

**Comment by arilamstein** [comment]
Ah, it appears to be as simple as:
```
    fig = px.choropleth_mapbox(df, 
                               ...
                               hover_data={var_label: ":$,"},
```
Also, this formatting should probably be included for median rent as well (but not for population). 
                               hover_data={var_label: ":$,"},

**Comment by arilamstein** [comment]
The solution is now in production.
